// aot_main_wrapper.c
//
// Main function wrapper for AOT-compiled FasterBASIC programs.
//
// Problem:
//   Graphics/audio require NSApplication event loop on main thread.
//   AOT programs generate main() that runs user code directly.
//   We need: main thread → event loop, worker thread → user code.
//
// Solution:
//   The LLVM codegen generates __basic_user_main() with the user's code.
//   This file provides the actual main() that:
//     1. Detects if graphics/audio are needed (by checking for window creation)
//     2. If needed, calls fbc_run_with_appkit() to set up threading
//     3. Otherwise, runs user code directly (for simple programs)
//
// This wrapper is linked into all AOT executables.

#include <stdio.h>
#include <stdbool.h>
#include <pthread.h>

// ─── External symbols ────────────────────────────────────────────────────────

// User's compiled program (generated by LLVM codegen)
extern int __basic_user_main(void);

// AppKit lifecycle hooks (implemented in aot_appkit_init.m)
extern void aot_appkit_init_if_needed(void);
extern void aot_appkit_run_event_loop(void);
extern void aot_appkit_shutdown(void);

typedef struct {
    void (*work)(void *);
    void *context;
} AppKitRunCtx;

static void *fbc_worker_thread_main(void *opaque) {
    AppKitRunCtx *ctx = (AppKitRunCtx *)opaque;
    ctx->work(ctx->context);

    // Stop NSApp loop on main thread once BASIC worker finishes.
    aot_appkit_shutdown();
    return NULL;
}

static void fbc_run_with_appkit(void (*work)(void *), void *context) {
    aot_appkit_init_if_needed();

    AppKitRunCtx run_ctx = { .work = work, .context = context };
    pthread_t worker;
    if (pthread_create(&worker, NULL, fbc_worker_thread_main, &run_ctx) != 0) {
        // Fallback: run inline if worker creation fails.
        work(context);
        return;
    }

    aot_appkit_run_event_loop();
    (void)pthread_join(worker, NULL);
}

// Runtime initialization/cleanup (basic_runtime.c)
extern void basic_runtime_init(void);
extern void basic_runtime_cleanup(void);

// ─── Worker thread wrapper ───────────────────────────────────────────────────

typedef struct {
    int exit_code;
} WorkerContext;

static void aot_worker_main(void *ctx) {
    WorkerContext *context = (WorkerContext *)ctx;
    
    // Initialize the runtime
    basic_runtime_init();
    
    // Run the user's program
    context->exit_code = __basic_user_main();
    
    // Clean up
    basic_runtime_cleanup();
}

// ─── Main entry point ────────────────────────────────────────────────────────

int main(int argc, char **argv) {
    (void)argc;
    (void)argv;
    
    // Always use AppKit threading model for AOT programs.
    // This ensures graphics/audio work properly.
    // For programs that don't use graphics, the overhead is minimal
    // (just pthread_create + NSApp event loop that sits idle).
    
    WorkerContext context = { .exit_code = 0 };
    
    fbc_run_with_appkit(aot_worker_main, &context);
    
    return context.exit_code;
}